@startuml

package ucf.assignments #ADD {

    class InventoryManager {
        + {static} main(String[] args): void
        + start(Stage primaryStage): void
    }

    interface Serializer {
        + from(String items): Collection<? extends Item>
        + to(Collection<? extends Item> items): String
    }

    class InventoryJSONSerializer {
        + from(String items): Collection<? extends Item>
        + to(Collection<? extends Item> items): String
    }

    class InventoryHTMLSerializer {
        + from(String items): Collection<? extends Item>
        + to(Collection<? extends Item> items): String
    }

    class InventoryTSVSerializer {
        + from(String items): Collection<? extends Item>
        + to(Collection<? extends Item> items): String
    }

    class InventoryManagerModel {
        - itemMap : ObservableMap<String,Item>
        - itemList : ObservableList<Item>
        - filteredItemList : FilteredList<Item>
        - sortedItemList : SortedList<Item>

        - dataAccessObject : InventoryDAO
    }

    class Item {
        - name : String
        - serialNumber : String
        - value : BigDecimal
    }

    class InventoryManagerController {
         # Event Handlers()
    }

    interface InventoryDAO {
        + create(): void
        + getItems(): Collection<? extends Item>
        + saveItems(Collection<? extends Item> items): void
        + delete(): void
    }

    class InventoryFileDAO {
        - path : Path
        - serializer : Serializer

        + InventoryFileDAO(Path path): InventoryDAO

        + create(): void
        + getItems(): Collection<? extends Item>
        + saveItems(Collection<? extends Item> items): void
        + delete(): void

        - determineFileExtension(Path path): <? extends Serializer>
    }
}

InventoryManager -- InventoryManagerController
InventoryManagerController *-- InventoryManagerModel
InventoryManagerModel *-- InventoryDAO
Item -* InventoryManagerModel
InventoryFileDAO *- Serializer
Serializer <|.. InventoryJSONSerializer
Serializer <|.. InventoryHTMLSerializer
Serializer <|.. InventoryTSVSerializer
InventoryDAO <|.. InventoryFileDAO
Item .. InventoryDAO

@enduml